version: "3"
services:
  front:
    #Para realizar build local
    # container_name: sample2021
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: eltonq15/cadastro-pessoas-frontend:1.0.0
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true